// Generated by CoffeeScript 1.7.1
(function() {
  var compressor;

  compressor = require("yuicompressor");

  compressor.compress("test.min.js", {
    charset: 'utf8',
    type: "js",
    nomunge: true,
    "line-break": 80
  }, function(err, data, extra) {
    if (err) {
      console.log(err);
      return;
    }
    return console.log(data);
  });

}).call(this);
