#定义task格式：task  名称， 描述， 任务函数
#invoke 名字，会调用相应的task，使任务连续执行

fs = require 'fs'

option '-o', '--output [DIR]', 'directory for compiled code'

task 'build:parser', 'rebuild the Jison parser', (options) ->
  require 'jison'
  #code = require('./lib/grammar').parser.generate()
  dir  = options.output or 'lib'
  #fs.writeFile "#{dir}/parser.js", code
  invoke 'build'