// Generated by CoffeeScript 1.7.1
(function() {
  var age, args, cdown, child, courses, dish, event, filename, food, footprints, grade, i, mood, name, num, olds, score, solipsism, speed, x, zip, _fn, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1,
    __hasProp = {}.hasOwnProperty;

  if (!(singing && !q)) {
    mood = greatlyImproved;
  }

  if (sing === 1) {
    mood = greatlyImproved;
    mood = 2;
  }

  if (sing === 1) {
    mood = greatlyImproved;
    mood = 2;
  }

  if (hehe && xixi) {
    mood = 2;
  }

  if (hehe || xixi) {
    mood = 2;
  }

  _ref = ['toast', 'cheese', 'wine'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    food = _ref[_i];
    eat(food);
  }

  courses = ['greens', 'caviar', 'truffles', 'roast', 'cake'];

  for (i = _j = 0, _len1 = courses.length; _j < _len1; i = ++_j) {
    dish = courses[i];
    menu(i + 1, dish);
  }

  for (i = _k = 0, _len2 = courses.length; _k < _len2; i = ++_k) {
    dish = courses[i];
    if (dish === caviar) {
      play(dish);
    }
  }

  cdown = ((function() {
    var _l, _results;
    num("as");
    _results = [];
    for (num = _l = 10; _l >= 1; num = --_l) {
      _results.push(true);
    }
    return _results;
  })());

  event = (function() {
    var _l, _results;
    _results = [];
    for (x = _l = 2; _l <= 8; x = _l += 2) {
      _results.push(x);
    }
    return _results;
  })();

  olds = {
    lili: 10,
    mama: 99,
    nima: 100
  };

  args = (function() {
    var _results;
    _results = [];
    for (child in olds) {
      age = olds[child];
      _results.push("" + child + " is " + age);
    }
    return _results;
  })();

  for (name in olds) {
    if (!__hasProp.call(olds, name)) continue;
    name;
  }

  if (this.studyingEconomics) {
    while (supply > demand) {
      buy();
    }
    while (!(supply > demand)) {
      sell();
    }
  }

  _fn = function(filename) {
    return fs.readFile(filename, function(err, contents) {
      return compile(filename, contents.toString());
    });
  };
  for (_l = 0, _len3 = list.length; _l < _len3; _l++) {
    filename = list[_l];
    _fn(filename);
  }

  if ((typeof mind !== "undefined" && mind !== null) && (typeof world === "undefined" || world === null)) {
    solipsism = true;
  }

  speed = 0;

  if (speed == null) {
    speed = "aa";
  }

  footprints = typeof yeti !== "undefined" && yeti !== null ? yeti : "bear";

  zip = typeof lottery.drawWinner === "function" ? (_ref1 = lottery.drawWinner().address) != null ? _ref1.zipcode : void 0 : void 0;

  switch (day) {
    case "Mon":
      go(work);
      break;
    case "TUE":
      go(relex);
      break;
    case "Fri":
    case "Sat":
      if (day === bingoDay) {
        go(bingo);
        go(dancing);
      }
      break;
    default:
      go(work);
  }

  score = 76;

  grade = (function() {
    switch (false) {
      case !(score < 60):
        return 'F';
      case !(score < 70):
        return 'D';
      case !(score < 80):
        return 'C';
      case !(score < 90):
        return 'B';
      default:
        return 'A';
    }
  })();

}).call(this);
