// Generated by CoffeeScript 1.7.1
(function() {
  var change, inner, outer;

  this.outer = 1;

  outer = 3;

  change = function(div) {
    var inner;
    inner = -1;
    return outer = 6;
  };

  inner = change();

  div += "a";

}).call(this);
