// Generated by CoffeeScript 1.7.1
(function() {
  var Account, Animal, Horse, Snake, sam, tom,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Animal = (function() {
    function Animal(name, age) {
      this.age = age;
      this.name = name + "a";
    }

    Animal.attr = 'title';

    Animal.prototype.type = "text";

    Animal.prototype.move = function(meters) {
      return alert(this.name + ("move " + meters + "m."));
    };

    return Animal;

  })();

  Snake = (function(_super) {
    __extends(Snake, _super);

    function Snake(name) {
      this.name = name;
    }

    Snake.prototype.move = function() {
      alert("slithering...");
      return Snake.__super__.move.call(this, 5);
    };

    return Snake;

  })(Animal);

  Horse = (function(_super) {
    __extends(Horse, _super);

    function Horse() {
      return Horse.__super__.constructor.apply(this, arguments);
    }

    Horse.prototype.move = function() {
      alert("gallop...");
      return Horse.__super__.move.apply(this, arguments).move(45);
    };

    return Horse;

  })(Animal);

  sam = new Snake("Sammy the Python");

  tom = new Horse("Tommy the Palomino");

  sam.move();

  tom.move();

  String.prototype.dasherize = function() {
    return this.replace(/_/g, "-");
  };

  Account = function(customer, cart) {
    this.customer = customer;
    this.cart = cart;
  };

  $(".shopping").bind("click", (function(_this) {
    return function(event) {
      return _this.customer.purcher(_this.cart);
    };
  })(this));

}).call(this);
