// Generated by CoffeeScript 1.7.1
(function() {
  var OPERATOR, cholesterol, error, healthy, hi, html;

  hi = function() {
  return [document.title, "Hello JavaScript"].join(": ");
};

  try {
    allHellBreaksLoose();
    catsAndDogsLivingTogether();
  } catch (_error) {
    error = _error;
    print(error);
  } finally {
    cleanUp();
  }

  cholesterol = 127;

  healthy = (200 > cholesterol && cholesterol > 60);

  html = "<strong>\n  cup of coffeescript\n</strong>";

  OPERATOR = /^(?:[-=]>|[-+*\/%<>&|^!?=]=|>>>=?|([-+:])\1|([&|<>])\2=?|\?\.|\.{2,3})/;

}).call(this);
