// Generated by CoffeeScript 1.7.1

/*
    最后一句默认自动return， 可加true 或null
 */

(function() {
  var contenders, error, fill, medias,
    __slice = [].slice;

  fill = function(contain, div) {
    if (div == null) {
      div = "coffee";
    }
    div += "asa";
    contain.push(div);
    return true;
  };

  fill = function(contain, div) {
    if (div == null) {
      div = "coffee";
    }
    div += "asa";
    return contain.push(div);
  };

  medias = function() {
    var first, g, others, rest, s, second;
    first = arguments[0], second = arguments[1], others = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    g = first;
    s = second;
    rest = others;
    return true;
  };

  contenders = ["Michael Phelps", "Liu Xiang", "Yao Ming", "Allyson Felix", "Shawn Johnson", "Roman Sebrle", "Guo Jingjing", "Tyson Gay", "Asafa Powell", "Usain Bolt"];

  medias.apply(null, ["ass", "zz"].concat(__slice.call(contenders)));

  alert((function() {
    try {
      return non / void 0;
    } catch (_error) {
      error = _error;
      return "有错误" + error;
    }
  })());

  Math.pow(2, 5);

}).call(this);
