// Generated by CoffeeScript 1.7.1
(function() {
  var Person, book, city, close, contents, copy, first, futuristits, last, name, numbera, numbers, open, people, songs, street, tag, text, theBait, theSwitch, tim, _i, _ref, _ref1, _ref2, _ref3, _ref4, _ref5,
    __slice = [].slice;

  book = {
    title: "abc",
    auther: "yjx"
  };

  people = {
    name: {
      firstName: "yan",
      lastName: "jixian"
    },
    sex: "male",
    "class": 3
  };

  log(people["class"]);

  songs = ["do", 2, "li", "hehe"];

  numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8];

  numbera = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  copy = numbers.slice(0);

  copy = numbers.slice(3, -1);

  [].splice.apply(numbers, [3, 4].concat(_ref = [-3, -4, -5, -6])), _ref;

  theBait = 1000;

  theSwitch = 0;

  _ref1 = [theSwitch, theBait], theBait = _ref1[0], theSwitch = _ref1[1];

  futuristits = {
    sculptor: "UB",
    painter: "VB",
    pont: {
      name: "FT",
      address: ["111", "222"]
    }
  };

  _ref2 = futuristits.poet, name = _ref2.name, (_ref3 = _ref2.address, street = _ref3[0], city = _ref3[1]);

  tag = "<impossible>";

  _ref4 = tag.split(""), open = _ref4[0], contents = 3 <= _ref4.length ? __slice.call(_ref4, 1, _i = _ref4.length - 1) : (_i = 1, []), close = _ref4[_i++];

  text = "Every literary critic believes he will outwit history and have the last word";

  _ref5 = text.split(" "), first = _ref5[0], last = _ref5[_ref5.length - 1];

  Person = (function() {
    function Person(options) {
      this.name = options.name, this.age = options.age, this.height = options.height;
    }

    return Person;

  })();

  tim = new Person({
    name: "tim"
  });

}).call(this);
